package com.bit.acc.model;

// default package
// Generated 2017-11-20 23:52:31 by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.*;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Coa generated by hbm2java
 */
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name = "COA", catalog = "acc")
@JsonIgnoreProperties(value={"createTime", "creator", "modifyTime", "modifier"}/*, ignoreUnknown = true*/)
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE, region="accStandardCache")
@Cacheable(true)
public class COA implements java.io.Serializable {

	private static final long serialVersionUID = -9213504593573999655L;

	@Id
    @GeneratedValue(generator="idgen")
	@GenericGenerator(name="idgen", strategy = "increment")
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountingStandardID", nullable = false)
	private AccountingStandard accountingStandard;
	
	@Column(name = "Code", nullable = false, length = 20)
	private String code;
	
	@Column(name = "Name", nullable = false, length = 50)
	private String name;
	
	@Column(name = "ElementCode", nullable = false, length = 20)
	private String elementCode;//会计要素名称，即科目分类名称
	
	@Column(name = "Status", nullable = false)
	private Boolean status;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", updatable = false, length = 19)
	@CreationTimestamp
	private Date createTime;
	
	@Column(name = "Creator")
	private Long creator;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyTime", length = 19)
	@UpdateTimestamp
	private Date modifyTime;
	
	@Column(name = "Modifier")
	private Long modifier;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coa")
	@Fetch(FetchMode.JOIN)
	@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	//@JsonManagedReference
	private Set<AccUsage> accUsages = new HashSet<AccUsage>(0);

	public COA() {
	}

	public COA(Long id, AccountingStandard accountingStandard, String code,
			String name, String elementCode, Boolean status) {
		this.id = id;
		this.accountingStandard = accountingStandard;
		this.code = code;
		this.name = name;
		this.elementCode = elementCode;
		this.status = status;
	}

	public COA(Long id, AccountingStandard accountingStandard, String code,
			String name, String elementCode, Boolean status, Date createTime, Long creator,
			Date modifyTime, Long modifier, Set<AccUsage> accUsages) {
		this.id = id;
		this.accountingStandard = accountingStandard;
		this.code = code;
		this.name = name;
		this.elementCode = elementCode;
		this.status = status;
		this.createTime = createTime;
		this.creator = creator;
		this.modifyTime = modifyTime;
		this.modifier = modifier;
		this.accUsages = accUsages;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public AccountingStandard getAccountingStandard() {
		return this.accountingStandard;
	}

	public void setAccountingStandard(AccountingStandard accountingStandard) {
		this.accountingStandard = accountingStandard;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getElementCode() {
		return this.elementCode;
	}

	public void setElementCode(String elementCode) {
		this.elementCode = elementCode;
	}

	public Boolean isStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Long getModifier() {
		return this.modifier;
	}

	public void setModifier(Long modifier) {
		this.modifier = modifier;
	}

	public Set<AccUsage> getAccUsages() {
		return this.accUsages;
	}

	public void setAccUsages(Set<AccUsage> accUsages) {
		this.accUsages = accUsages;
	}

}
