package com.bit.acc.model;

// default package
// Generated 2017-11-20 23:52:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Specificstandard generated by hbm2java
 */
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name = "specificstandard", catalog = "acc")
@JsonIgnoreProperties(value={"createTime", "creator", "modifyTime", "modifier"}/*, ignoreUnknown = true*/)
public class SpecificStandard implements java.io.Serializable {

	private static final long serialVersionUID = -8115220068759534373L;
	
	private Long id;
	private AccountingStandard accountingStandard;
	private String title;
	private String specifics;
	private Boolean status;
	private Boolean isPreface;
	private Date createTime;
	private Long creator;
	private Date modifyTime;
	private Long modifier;

	public SpecificStandard() {
	}

	public SpecificStandard(Long id, String title) {
		this.id = id;
		this.title = title;
	}

	public SpecificStandard(Long id, Boolean isPreface, String title, String specifics ) {
		this.id = id;
		this.isPreface = isPreface;
		this.title = title;
		this.specifics = specifics;
	}

	public SpecificStandard(Long id, AccountingStandard accountingStandard,
			String specifics, Boolean status) {
		this.id = id;
		this.accountingStandard = accountingStandard;
		this.specifics = specifics;
		this.status = status;
	}

	public SpecificStandard(Long id, AccountingStandard accountingStandard,
			String title, String specifics, Boolean status, Date createTime,
			Long creator, Date modifyTime, Long modifier) {
		this.id = id;
		this.accountingStandard = accountingStandard;
		this.title = title;
		this.specifics = specifics;
		this.status = status;
		this.createTime = createTime;
		this.creator = creator;
		this.modifyTime = modifyTime;
		this.modifier = modifier;
	}

	@Id
    @GeneratedValue(generator="idgen")
	@GenericGenerator(name="idgen", strategy = "increment")
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountingStandardID", nullable = false)
	public AccountingStandard getAccountingStandard() {
		return this.accountingStandard;
	}

	public void setAccountingStandard(AccountingStandard accountingStandard) {
		this.accountingStandard = accountingStandard;
	}

	@Column(name = "Title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Type(type="text")
	@Column(name = "Specifics", nullable = false, length = 65535)
	public String getSpecifics() {
		return this.specifics;
	}

	public void setSpecifics(String specifics) {
		this.specifics = specifics;
	}
	
	
	@Column(name = "IsPreface", nullable = false)
	public Boolean isIsPreface() {
		return isPreface;
	}

	public void setIsPreface(Boolean isPreface) {
		this.isPreface = isPreface;
	}

	@Column(name = "Status", nullable = false)
	public Boolean isStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", updatable = false, length = 19)
	@org.hibernate.annotations.CreationTimestamp
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "Creator")
	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyTime", length = 19)
	@org.hibernate.annotations.UpdateTimestamp
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "Modifier")
	public Long getModifier() {
		return this.modifier;
	}

	public void setModifier(Long modifier) {
		this.modifier = modifier;
	}

}
