package com.bit.acc.model;

// Generated 2016-7-2 16:40:42 by Hibernate Tools 4.0.0

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import javax.persistence.*;
import java.util.Date;

/**
 * SysLog generated by hbm2java
 */
@Entity
@Table(name = "SysLog")
@DynamicInsert(true)
@DynamicUpdate(true)
public class SysLog implements java.io.Serializable {

	/**
	 * generated serial id
	 */
	private static final long serialVersionUID = 8496799177052227038L;
	private Long id;
	//private Long enterpriseId;
	private String ip;
	private String cookie;
	private Long userId;/*
	private String mobile;
	private String email;
	private String nickName;*/
	private String log;
	private String entityName;
	private String operate;
	private String args;
	/*
	private String instance;
	private String attribute;
	private String oldValue;
	private String newValue;*/
	private Date oprtTime;/*
	private Date createTime;
	private Long creator;
	private Date modifyTime;
	private Long modifier;*/

	public SysLog() {
	}

	public SysLog(String ip, Long userId, String log, String entityName,
			String operate, String args,/*String instance, String attribute, String oldValue,
			String newValue,*/ Date oprtTime) {
		this.ip = ip;
		this.userId = userId;
		this.log = log;
		this.entityName = entityName;
		this.operate = operate;
		this.args = args;
		/*
		this.instance = instance;
		this.attribute = attribute;
		this.oldValue = oldValue;
		this.newValue = newValue;*/
		this.oprtTime = oprtTime;
	}

	@Id
    @GeneratedValue(generator="idgen")
	@GenericGenerator(name="idgen", strategy = "increment")
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "IP", nullable = false)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

    @Column(name = "Cookie", nullable = false)
	public String getCookie() {
		return cookie;
	}

	public void setCookie(String cookie) {
		this.cookie = cookie;
	}

	@Column(name = "UserID", nullable = true)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}
	
	
	@Column(name = "Log", nullable = false, length = 100)
	public String getLog() {
		return log;
	}

	public void setLog(String log) {
		this.log = log;
	}

	@Column(name = "EntityName", nullable = false, length = 64)
	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	@Column(name = "Operate", nullable = false, length = 32)
	public String getOperate() {
		return this.operate;
	}

	public void setOperate(String operate) {
		this.operate = operate;
	}

    @Type(type="text")
    @Column(name = "Args", nullable = false, length = 65535)
    public String getArgs() {
        return this.args;
    }

    public void setArgs(String args) {
        this.args = args;
    }

/*	@Column(name = "Instance", nullable = true, length = 64)
	public String getInstance() {
		return this.instance;
	}

	public void setInstance(String instance) {
		this.instance = instance;
	}

	@Column(name = "Attribute", nullable = true, length = 32)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "OldValue", nullable = true, length = 64)
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name = "NewValue", nullable = true, length = 64)
	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}*/

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OprtTime", nullable = false, length = 19)
	public Date getOprtTime() {
		return this.oprtTime;
	}

	public void setOprtTime(Date oprtTime) {
		this.oprtTime = oprtTime;
	}

    @Override
    public String toString() {
        return super.toString();
    }

/*
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", updatable = false, nullable = false, length = 19)
	@CreationTimestamp
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "Creator")
	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyTime", nullable = false, length = 19)
	@UpdateTimestamp
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "Modifier")
	public Long getModifier() {
		return this.modifier;
	}

	public void setModifier(Long modifier) {
		this.modifier = modifier;
	}*/

}
