package com.bit.acc.model;

// Generated 2016-7-2 16:40:42 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SysLog generated by hbm2java
 */
@Entity
@Table(name = "SysLog")
@DynamicInsert(true)
@DynamicUpdate(true)
public class SysLog implements java.io.Serializable {

	/**
	 * generated serial id
	 */
	private static final long serialVersionUID = 8496799177052227038L;
	private Long id;
	//private Long enterpriseId;
	private Long userId;
	private String entityName;
	private String operate;
	private String instance;
	private String attribute;
	private String oldValue;
	private String newValue;
	private Date oprtTime;
	private Date createTime;
	private Long creator;
	private Date modifyTime;
	private Long modifier;

	public SysLog() {
	}

	public SysLog(/*Long enterpriseId, */Long userId, String entityName,
			String operate, String instance, String attribute, String oldValue,
			String newValue, Date oprtTime) {
		//this.enterpriseId = enterpriseId;
		this.userId = userId;
		this.entityName = entityName;
		this.operate = operate;
		this.instance = instance;
		this.attribute = attribute;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.oprtTime = oprtTime;
	}

	@Id
    @GeneratedValue(generator="idgen")
	@GenericGenerator(name="idgen", strategy = "increment")
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/*@Column(name = "EnterpriseID", nullable = false)
	public Long getEnterpriseId() {
		return this.enterpriseId;
	}

	public void setEnterpriseId(Long enterpriseId) {
		this.enterpriseId = enterpriseId;
	}*/

	@Column(name = "UserID", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "EntityName", nullable = false, length = 64)
	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	@Column(name = "Operate", nullable = false, length = 32)
	public String getOperate() {
		return this.operate;
	}

	public void setOperate(String operate) {
		this.operate = operate;
	}

	@Column(name = "Instance", nullable = false, length = 64)
	public String getInstance() {
		return this.instance;
	}

	public void setInstance(String instance) {
		this.instance = instance;
	}

	@Column(name = "Attribute", nullable = false, length = 32)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "OldValue", nullable = false, length = 64)
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name = "NewValue", nullable = false, length = 64)
	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OprtTime", nullable = false, length = 19)
	public Date getOprtTime() {
		return this.oprtTime;
	}

	public void setOprtTime(Date oprtTime) {
		this.oprtTime = oprtTime;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", updatable = false, nullable = false, length = 19)
	@CreationTimestamp
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "Creator")
	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyTime", nullable = false, length = 19)
	@UpdateTimestamp
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "Modifier")
	public Long getModifier() {
		return this.modifier;
	}

	public void setModifier(Long modifier) {
		this.modifier = modifier;
	}

}
